@include('layouts.head')
    <body>
        @include('layouts.header')
        @yield('homeContent')
        @yield('content')
        @yield('contattiContent')
        @include('layouts.footer')
    </body>
</html>